In [1]:
## we can read LLM model from

# 1. Huggingface Hub(Finetuning chapter will discuss this HF in detail)
# 2. OpenAI SDK(Lang-chain)
# 2. Gemini SDK(Lang-chain)

# SDK (Software Development kit)
print(
    "All OKK"
)

All OKK


In [2]:
## Set it as a Envirment Variable

import os
os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_API_KEY")
os.environ["HF_TOKEN"] = os.getenv("HF_TOKEN")
# os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")

In [5]:
from sentence_transformers import SentenceTransformer

e:\Gen AI Bootcamp\Full-Stack-GenerativeAI-And-Agentic-AI-Bootcamp\myenv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## HuggingFace

In [6]:
## mini model => all-MiniLM-l6-v2

open_source_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

In [28]:
text = "machine"
open_source_embedding_model.encode(text)

array([-7.2135426e-02,  2.8487477e-02, -1.1770620e-02,  1.9800875e-02,
       -4.3478355e-02, -3.1459052e-02,  1.4960492e-02,  2.8898045e-03,
        3.2448636e-03, -3.3951893e-02,  1.0499174e-02, -1.0207248e-02,
        7.7768072e-02, -7.6556362e-02, -1.3995995e-03, -2.1019708e-03,
        1.7192375e-02, -6.3364789e-02, -2.8133729e-02, -5.8696937e-02,
       -3.2972585e-02,  1.0229135e-02, -6.4569518e-02,  1.9879974e-02,
       -1.0603138e-02,  1.0479343e-01, -3.8107079e-02,  5.0351795e-02,
        2.0600311e-02, -1.3008554e-01, -2.1826047e-02,  4.0763482e-03,
        6.2349136e-05,  2.9554119e-02,  3.2702241e-02, -1.5447503e-02,
        3.0989891e-02, -3.7602477e-02,  1.3706412e-02, -5.0064705e-02,
        2.3032054e-02, -7.9317793e-02, -8.2522556e-06, -1.9760652e-02,
        7.4942775e-02,  1.0247786e-01,  6.0151974e-03, -3.9858840e-02,
        5.4702215e-02,  3.1104805e-02, -1.1640596e-01, -7.0423111e-02,
        6.4530425e-02,  1.5530199e-02, -4.7102973e-02,  2.7658720e-02,
      

In [19]:
text_embedding = open_source_embedding_model.encode(text)  ## will get embedding


In [20]:
len(text_embedding)

384

In [21]:
text_embedding.shape

(384,)

In [22]:
sentence = "How to reduce heart disease risk?"
open_source_embedding_model.encode(sentence)

array([ 6.49378002e-02,  1.28513098e-01,  8.41135159e-03,  4.50837016e-02,
        6.74147392e-03,  2.71619726e-02, -7.06042275e-02,  2.64073405e-02,
       -3.79308090e-02, -2.38797162e-02, -6.41613407e-03, -1.86474493e-03,
        2.75909696e-02, -3.55664715e-02,  1.40230907e-02, -6.74080774e-02,
       -6.45455569e-02,  7.73962885e-02,  1.06312670e-02,  1.57817379e-02,
       -3.53638269e-02,  1.74660720e-02,  1.43505190e-03,  4.78440300e-02,
       -3.97442505e-02, -1.19458092e-02,  2.26337649e-03, -1.06840596e-01,
       -2.39676312e-02,  2.75908783e-02,  1.39234856e-01,  4.53191530e-03,
        7.27042779e-02,  1.19519401e-02, -7.98376650e-02,  5.52378595e-02,
        4.03933451e-02,  2.72679608e-02, -6.27351627e-02,  2.34903786e-02,
        8.01412296e-03, -4.28504795e-02, -5.53445611e-03,  6.84070680e-03,
        3.87947969e-02,  5.79556869e-03, -2.26256251e-02,  2.16251751e-03,
        5.31850047e-02,  3.31053650e-03, -8.02946165e-02,  4.53440426e-03,
       -8.07447881e-02, -

In [23]:
sentence_embedding = open_source_embedding_model.encode(sentence)

In [24]:
len(sentence_embedding)

384

In [25]:
paragraph = """
Machine learning is a field of artificial intelligence that focuses on building systems 
that learn from data. It is widely used in applications like recommendation systems, 
image recognition, and natural language processing.
"""
open_source_embedding_model.encode(paragraph)


array([-2.78186835e-02, -6.40663877e-03,  3.68497409e-02,  2.21398147e-03,
        2.55084075e-02,  1.34022832e-02,  6.45564636e-03, -3.05501539e-02,
       -6.01916723e-02, -2.28518192e-02, -7.05490559e-02,  1.97643451e-02,
        5.54116182e-02, -3.38736363e-02, -9.74512007e-03,  4.72750813e-02,
       -1.58115327e-02, -1.64724048e-02, -6.00375757e-02, -7.00235516e-02,
        2.54246667e-02, -5.45068830e-03, -7.51983225e-02,  1.57804098e-02,
       -1.62698757e-02,  5.30246496e-02,  6.29330799e-02,  1.47748636e-02,
       -1.32339103e-02,  5.44603169e-03,  2.14249045e-02, -3.44793051e-02,
        1.16899237e-02,  4.35766503e-02, -4.42826338e-02,  5.05335741e-02,
       -2.66971812e-02,  5.36212046e-03,  7.96870608e-03, -1.89670064e-02,
       -6.25875071e-02, -7.47380778e-02,  6.55538449e-03, -6.77178055e-03,
        1.26145586e-01,  1.28760293e-01, -7.31318370e-02, -9.79880542e-02,
        8.16455460e-04,  1.73747428e-02, -1.05541252e-01,  1.18358359e-02,
       -1.23240501e-02,  

In [26]:
paragraph_embedding = open_source_embedding_model.encode(paragraph)
len(paragraph_embedding)

384

In [27]:
# for each embedding (text_embedding, sentence_embedding and paragraph_embedding) len is 384 dinemtion

## GEMINI

In [29]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings

In [31]:
google_embeddings_model = GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

In [33]:
embedding = google_embeddings_model.embed_query("whar is the capital of India?")
embedding

[-0.020485425,
 -0.004599759,
 0.007110898,
 -0.054253504,
 -0.04684005,
 -0.013011512,
 0.019909723,
 0.0011694827,
 -0.0034329975,
 -0.009409937,
 -0.034439083,
 -0.0023239728,
 0.0020862117,
 0.026197322,
 0.1236729,
 -0.014336934,
 -0.011456002,
 0.0054796394,
 0.009391598,
 -0.007389723,
 -0.015827477,
 0.008279208,
 0.024674367,
 -0.008511349,
 0.012292365,
 0.005591664,
 0.006236833,
 -0.008647191,
 0.021625508,
 0.00583983,
 -0.009490615,
 -0.028175564,
 0.019098237,
 -0.025238475,
 0.027537702,
 0.004880322,
 0.0034538177,
 0.020475874,
 0.0011742437,
 -0.0027520577,
 -0.027466642,
 0.00012550042,
 0.02351081,
 0.0010287768,
 -0.0047222683,
 -0.00528859,
 0.017310381,
 -0.0374841,
 -0.0022081463,
 0.03789279,
 -0.00080560596,
 -0.012187622,
 -0.045996968,
 -0.17825897,
 -0.008959288,
 0.028691968,
 0.0022426106,
 -0.014225696,
 -0.012446225,
 -0.0035136247,
 -0.012559254,
 0.0070369523,
 -0.015730798,
 -0.014225174,
 0.0015759588,
 0.03114825,
 -0.0075363843,
 0.014872272,
 -0

In [ ]:
len(embedding)  ##vector size #dimention

3072

## Images

In [ ]:
# TEXT

# IMAGE?

# ViT(vision transformer) and CLIP(contrastive language-image pretraining) are two popular transformer-based models used for image processing tasks.

In [41]:
from transformers import CLIPModel, CLIPProcessor

In [42]:
from PIL import Image

In [43]:
img = Image.open("E:\Gen AI Bootcamp\Full-Stack-GenerativeAI-And-Agentic-AI-Bootcamp\Class 09_18April26 SOTA, Transformer Embedding Methods\image\lion.png")

In [44]:
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
e:\Gen AI Bootcamp\Full-Stack-GenerativeAI-And-Agentic-AI-Bootcamp\myenv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ICON\.cache\huggingface\hub\models--openai--clip-vit-base-patch32. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows

In [45]:
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


KeyboardInterrupt: 

In [ ]:
imput = processor(images=img, return_tensors="pt")

In [ ]:
import torch

In [46]:
# Get embedding
with torch.no_grad():
    image_embedding = model.get_image_features(**input)

NameError: name 'torch' is not defined

## Semantic Search (Similarity Search)

In [47]:
# 1. Dot Product
# 2. Cosine Similarity
# # 3. Eculidean Distance(L2)

In [ ]:
# Formulas for Dot Product 

def dot_product(a, b):
    return np.dot(a, b)

In [ ]:
# Formulas for cosine_similarity


def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
# Formulas for euclidean_distance


def euclidean_distance(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.linalg.norm(a - b)

In [59]:
print("=== Cosine Similarity (Higher is better) ===")
print("Range: -1 to 1")

print("\n=== Dot Product (Higher is better) ===")
print("Range: -∞ to +∞ (depends on vector magnitude)")

print("\n=== Euclidean Distance (Lower is better) ===")
print("Range: 0 to +∞")

=== Cosine Similarity (Higher is better) ===
Range: -1 to 1

=== Dot Product (Higher is better) ===
Range: -∞ to +∞ (depends on vector magnitude)

=== Euclidean Distance (Lower is better) ===
Range: 0 to +∞


In [50]:
query = "How to reduce heart disease risk?"

In [54]:
documents = [
    "Eating fiber reduces heart risk.",
    "Fruits and vegetables lower cardiovascular disease chances.",
    "Buying a new car improves driving comfort.",
    "Regular exercise improves heart health."
]

In [56]:
query_embedding = google_embeddings_model.embed_query(query)
len(query_embedding)

3072

In [57]:
doc_embedding = google_embeddings_model.embed_query(documents)
len(doc_embedding)

3072

In [58]:
len(doc_embedding[0])

TypeError: object of type 'float' has no len()